# Proje Başvurusu (Seçilen kısımlar) 

###Amaç / Gerekçe
Hiç bir ticari çıkar gözetmeksizin hazırlanacak bu çalışmaların, R gibi dünyaya kendini ispatlamış ve ücretsiz olan bir programın ülkemizde de yaygınlaşmasına biraz olsun katkı sağlayabileceğini umuyorum. Eğitim alanında çalışan ve çalışacak araştırmacıların R ile tanışmak istediklerinde kullanabileceği dokümanlar ortaya çıkacaktır. Doküman halka açık bir çevrimiçi depoda tutulacaktır. Dokümanların kabul görmesi durumunda, kullanıcılardan gelen istekleri ve önerileri hızlı bir şekilde dokümanlara dahil ederek, ihtiyaçlara cevap verme ihtimali yüksek olan bir kaynağın ortaya çıkmasını umuyorum.
R programlama dilini öğrenmiş araştırmacılara vakit kazandırmak, R programlama dilinde istediği gelişmeyi gösteremeyen araştırmacılara yardımcı olmak amacıyla hazırlanacak R tabanlı interaktif web uygulamalarına temel teşkil edecek özgün bir eser ortaya çıkmasını umuyorum.
Ülkemizin, diğer her alanda olduğu gibi, eğitim alanında yapılan araştırmalar için kullanılan yazılımlar anlamında da kendi kendine yeter duruma gelebilmesi, diğer ülkelerde yaşanan gelişmeleri daha yakından takip edebilmesi ve yeni gelişmelere öncü olabilmesi için R programlama becerisinin araştırmacılara kazandırılmasının önemli olduğunu düşünüyorum. Her ne kadar öğrenme eğrisi oldukça dik olsa da, programlama becerileri günümüz dünyasında bir zorunluluk haline dönüşmektedir. Stephen Hawking’inde belirttiği gibi, “evrenin gizemini çözmek için ya da 21. yüzyıl dünyasında herhangi bir kariyere sahip olmak için bireylerin programlama becerisine sahip olması gerekmektedir.” 


### Konu/Kapsam
Eğitim alanında yapılan nicel araştırmalardan elde edilen sonuçların sistematik ve nesnel olarak yorumlanabilmesi için istatistiksel yöntemler kullanılmaktadır. Bu prosedürlerin tamamlanması çoğu zaman ücretli yazılımlar ile sağlanır, örneğin SPSS, SAS, Lisrel, AMOS. Ülkemizde üniversiteler bu yazılımlar için maalesef ciddi bütçeler ayırmak zorunda kalmaktadır. Araştırmacıların bu pahalı programlara ulaşmak için zaman zaman yazılım korsanlığına başvurmaları ise daha büyük bir sorun oluşturmaktadır. Eğitim alanında çalışan araştırmacıların bu ücretli (proprietary) yazılımları kullanmanın dışında başka bir alternatifleri açık kaynak (open source) tabanlı programlar olabilir. Bu araştırma önerisi, açık kaynak kodlu ve ücretsiz bir programlama dili olan R’ın eğitim alanında yapılan araştırmalarda daha yaygın kullanılabilmesini sağlamak için hazırlanacak materyallerle ve verilebilecek eğitimlerle ilgilidir.  
Robert Muenchen (2011), R’ın yakın gelecekte veri analizi için kullanılan evrensel bir programlama dili olacağını söyleyerek yeni metodların SPSS ve SAS gibi yaygın yazılımlardan daha önce R’da tanıtıldığını vurgulamaktadır. Aynı zamanda Muenchen, kişisel web sitesinde 2014 yılında yayınladığı bir makalede  R programının analitik akademik yayınlarda en çok kullanılan üçüncü yazılım paketi olduğunu, ücretsiz olanların içinde ise ilk sırada olduğunu belirtmiştir. Son yıllarda Harvard ve Oxford gibi tanınmış üniversiteler de R programlama dili üzerine çalıştaylar düzenlemektedirler . R programlama dilini öğretmek için hazırlanmış birçok İngilizce kitlesel açık çevrimiçi kurslar da bulunmaktadır . Microsoft, Google ve Ford gibi dünyaca bilinen şirketler de kullandığı programlar arasında R’a yer vermişlerdir . 
Data analizi ve istatistiksel modellemenin yanında, işlevsel grafikler çizme, dokümanlar oluşturma, sunum hazırlama ve simülasyon üretme gibi çeşitli amaçlar için kullanılabilen R, başta istatistikçiler olmak üzere, mühendisler, ekonometristler ve sosyal bilimlerde modern ve komplike modellerle çalışan araştırmacıların dikkatini çekmiştir.

### Literatür özeti
R programını tanıtım amaçlı birçok yabancı kaynak bulunmaktadır. Kullanıldığı amaca göre oldukça teknik olabilen bu kaynakların içinde sosyal bilimciler için uygun olabilecek kaynaklardan bazıları şunlardır; (a) Field, Miles ve Field (2012), sosyal bilimlerde sıkça kullanılan modelleri (örneğin t-test, korelasyon, ANOVA, regresyon) çoğunluğu psikoloji alanında toplanmış verilerlerin analizi için kullanmıştır, (b) Dalgaard (2008) , Field’a oranla daha teknik bir dil ile yazılmış bu kitap, sosyal bilimcilerin sıkça kullandığı modelleri teorik altyapıları ile birlikte sunmuştur, (c) Everitt ve Hothorn (2011), ölçek geliştirme ve geçerlik çalışmalarında kullanılan faktör analizlerini içeren bir uygulama kitabı yazmıştır. Ücretsiz olan ve birçok gelişmiş analize öncülük eden R programlama dilinin tanıtımı ve yaygınlaştırılması ise Avrupa ve Amerika’ya oranla  Türkiye’de neredeyse hiç yapılmamıştır. Türkçe kaynaklar R’ın kısa tanıtımını yapan ve istatistik bölümü öğretim üyeleri tarafından hazırlanmış kitaplar (Sönmez, 2006; Satman, 2010; İlk,2011; Gürsakal, 2014),  bir kaç blog yazısı ve konferans bildirileri ile sınırlı kalmıştır. (Baydoğan ve Çetin, 2014; Özdemir, Yıldıztepe ve Binar, 2010).  Bununla beraber Google Scholar ve ulusal veri tabanlarında, sosyal bilimcilere yönelik ucretli ya da ucretsiz Türkçe bir R kaynağı bulunamamıştır.

### Özgün Değeri
Tanınmış üniversitelerden, tanınmış bilim insanlarından ve büyük şirketlerden saygı gören R programının ülkemizde de yaygınlaşması ekonomik tasarrufun yanı sıra alanın öncülerine yetişme imkanı da sağlayabilir. Kalkınma Bakanlığının yayınladığı çalışma raporunda, Milli Savunma Bakanlığının açık kaynak kodlu yazılımların kullanılması sonucu sadece lisans bedellerinde 2012 yılı ve öncesinde yaklaşık 2 milyon Amerikan doları tasarruf edildiği belirtilmiştir . Bu çalışma, açık kaynak kodlu yazılımların kullanılması doğrultusunda, sosyal bilimler alanında atılacak ilk adımlardan biri olma niteliğindedir. Çalışmanın amacı, eğitim alanındaki araştırmacılara yönelik hazırlanacak olan R materyallerine zemin oluşturabilecek özgün bir tanıtım ve uygulama kılavuzu niteliğinde dokümanlar hazırlamaktır. Hazırlanacak dokümanlar Türkiye’de eğitim alanında toplanmış veriler üzerine inşa edilecektir. Daha sonra Türkçeye çevrilmek üzere İngilizce olarak hazırlanacak tanıtım dökümanı, programın kurulumunu, basit fonksiyonlarını, veri girdisi ve çıktısının nasıl yapılabileceğini, betimsel analizleri, basit grafik çizimlerini, t-test, varyans analizlerini, korelasyon ve regresyon analizlerini kapsayacaktır. Teorik altyapıya kısaca değinilecek, sonuçları raporlama süreci ise daha ayrıntılı verilecektir. Uygulama kılavuzu Türkçe olarak hazırlanacak ve eğitim etkinliklerinin çerçevesini oluşturacaktır. Ortaya çıkan ürünler, şu an çalıştığım kurum öncelikli olmak üzere yurt içinde verilecek çalıştaylar için kullanılabilecektir. Araştırmanın gerçekleşmesi halinde, programın yaygınlaşmasını sağlayabilecek gelişmiş R materyalleri  için de zemin oluşacaktır. 

### Yaygın etki/katma değer
Amaç bölümünde belirtildiği gibi doküman halka açık bir çevrimiçi depoda tutulacak ve üniversitelerin eğitim fakültelerine elektronik posta ile tanıtılacaktır. Dokümanların kabul görmesi durumunda, kullanıcılardan gelen istekleri ve önerileri hızlı bir şekilde dokümanlara dahil ederek, ihtiyaçlara cevap verme ihtimali yüksek olan bir kaynak ortaya çıkabilir. Yine özgün değer bölümünde belirttiğim gibi, tamamen açık kaynak üzerinden çalışan R programının, ülkemizde yaygınlaşması durumunda ithal yazılım gerekliliğini azaltarak tasarruf etme ihtimali mevcuttur.

### Genel tavsiye
1) eksikler var 
